"""
Report Agent: Generates a side-by-side vendor comparison report in Markdown.
"""
from datetime import datetime
import os


def _fmt_usd(val):
    """Safely format a USD value, handling None."""
    if val is None:
        return "N/A"
    try:
        return f"${val:,.0f}"
    except (TypeError, ValueError):
        return str(val)


def _fmt_pct(val):
    """Safely format a percentage, handling None."""
    if val is None:
        return "N/A"
    try:
        return f"{val:+.1f}%"
    except (TypeError, ValueError):
        return str(val)


def run_report_generator(all_evaluations: list, company_requirements: dict) -> str:
    """
    Generates a Markdown comparison report from all vendor evaluations.
    Saves to templates/output/Vendor_Comparison_Report.md
    """
    project_name = company_requirements.get("project_name", "Untitled Project")
    budget = company_requirements.get("budget_limit_usd", None)
    budget_str = _fmt_usd(budget)

    # Sort by overall score (highest first)
    ranked = sorted(all_evaluations, key=lambda x: x.get("overall_score", 0), reverse=True)

    md = f"""# Vendor Comparison Report: {project_name}

**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Vendors Evaluated:** {len(ranked)}
**Budget Limit:** {budget_str} USD

---

## Ranking Summary

| Rank | Vendor | Overall | Technical | Compliance | Price | Proposed Cost |
|------|--------|---------|-----------|------------|-------|---------------|
"""

    for i, ev in enumerate(ranked, 1):
        medal = ["1st", "2nd", "3rd"][i - 1] if i <= 3 else f"{i}th"
        price = ev.get("proposed_price_usd", 0) or 0
        within = "Yes" if budget and price <= budget else "NO" if budget else "?" # type: ignore
        md += f"| {medal} | {ev.get('vendor_name', 'Unknown')} | **{ev.get('overall_score', 0)}** | {ev.get('technical_score', 0)} | {ev.get('compliance_score', 0)} | {ev.get('price_score', 0)} | {_fmt_usd(price)} ({within}) |\n"

    md += f"""
---

## Recommended Vendor: {ranked[0].get('vendor_name', 'Unknown')} (Score: {ranked[0].get('overall_score', 0)}/100)

---

## Detailed Vendor Assessments
"""

    for i, ev in enumerate(ranked, 1):
        price = ev.get("proposed_price_usd", 0) or 0
        md += f"""
### {i}. {ev.get('vendor_name', 'Unknown')} (Overall: {ev.get('overall_score', 0)}/100)

| Dimension | Score | Details |
|-----------|-------|---------|
| Technical | {ev.get('technical_score', 0)}/100 | {ev.get('engineering_notes', 'N/A')} |
| Compliance | {ev.get('compliance_score', 0)}/100 | {ev.get('compliance_notes', 'N/A')} |
| Price | {ev.get('price_score', 0)}/100 | {_fmt_usd(price)} vs budget {budget_str} |

"""
        # Market validation table
        market_data = ev.get("market_validation", [])
        if market_data:
            md += "**Market Price Validation:**\n\n"
            md += "| Material | Vendor Price | Market Price | Markup | Verdict |\n"
            md += "|----------|-------------|-------------|--------|--------|\n"
            for m in market_data:
                mp = _fmt_usd(m.get("market_price"))
                vp = _fmt_usd(m.get("vendor_price", 0))
                markup = _fmt_pct(m.get("markup_pct"))
                md += f"| {m.get('material', '?')} | {vp} | {mp} | {markup} | {m.get('verdict', '?')} |\n"
            md += "\n"

    md += "\n---\n*Report generated by Agentic Vendor Evaluation System.*\n"

    # Save
    os.makedirs("templates/output", exist_ok=True)
    file_path = "templates/output/Vendor_Comparison_Report.md"
    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(md)
        print(f"   -> Report saved to: {file_path}")
    except Exception as e:
        print(f"   Error saving report: {e}")

    return md


if __name__ == "__main__":
    test_evals = [
        {"vendor_name": "AlphaTech", "overall_score": 72, "technical_score": 90, "compliance_score": 85, "price_score": 30, "proposed_price_usd": 2045000, "engineering_notes": "Excellent", "compliance_notes": "Full certs"},
        {"vendor_name": "GammaMfg", "overall_score": 80, "technical_score": 85, "compliance_score": 90, "price_score": 65, "proposed_price_usd": 842500, "engineering_notes": "Good", "compliance_notes": "Strong"},
    ]
    test_reqs = {"project_name": "Test Project", "budget_limit_usd": 850000}
    print(run_report_generator(test_evals, test_reqs))
